### ISSUE TITLE
Embedding and Data sources empty 

### ISSUE THREAD

**Issue by judavi** [truefoundry/cognita#156]
Hello Cognita team!
I bumped with the project and I found it very interesting. I'm currently running the code on localmachine but I've notice that I can't do anything because I can't create new collections
![image](https://github.com/truefoundry/cognita/assets/1766933/8c2d6a18-1688-42c4-8e57-00058de4000e)
Both the Embedding and Data sources are empty.
I'm not seeing anything relevant in the console
<img width="657" alt="image" src="https://github.com/truefoundry/cognita/assets/1766933/521fa13f-ba22-4962-83af-ba3370d9cf84">
But I can see 400 in browser console
![image](https://github.com/truefoundry/cognita/assets/1766933/376567ad-3b0c-4115-94b8-135e9ff0bbb9)
Any advice on what I could be missing? Thanks for the help!

**Comment by swapnil34** [comment]
Probable solution: Make sure that your .env file has following variable set correctly for the frontend:
`VITE_QA_FOUNDRY_URL=http://localhost:8000`

**Comment by S1LV3RJ1NX** [comment]
Also, if you are running locally, you can create collections using `local.metadata.yaml` and that will be directly visible through UI.
