### ISSUE TITLE
Why do have two env example/sample files in the root folder?

### ISSUE THREAD

**Issue by avibathula** [truefoundry/cognita#192]
As of now, root folder has
- An `env.example` file 
- An `env.local.example` file

It would be helpful to clean up the .env sample/example files

**Comment by S1LV3RJ1NX** [comment]
The local example file is for when you run cognita locally, the other one is for truefoundry specifics. We are in process of refactoring and clean up will get this done soon!

**Comment by S1LV3RJ1NX** [comment]
We have now moved to docker compose, keeping only a single env file. Please check the docs now. Thanks!
