### ISSUE TITLE
Metadata Aware retrieval

### ISSUE THREAD

**Issue by AchintyaX** [truefoundry/cognita#197]
Does Cognita Support advanced RAG techniques like Vectorindex Auto -retrievers, where the LLM extracts metadata features from the query to make Vector Search more enriched with query filters

**Comment by S1LV3RJ1NX** [comment]
You can add these in the query controller section logic similar to contextual compression retrievers or multi-query retriever logic. These questions are better suited as discussions, rather than issues.
