### ISSUE TITLE
DataSource type not show

### ISSUE THREAD

**Issue by AlifAbhiesa** [truefoundry/cognita#202]
After install using docker composer by default env, the data source type doesnt show, so i cant add any data.

![image](https://github.com/truefoundry/cognita/assets/27193997/bde3f5ba-44c5-4bfb-b7bd-02f440cdcef3)

**Comment by S1LV3RJ1NX** [comment]
Data sources should show, it might take some time to start the BE before connects with FE. Also when using locally, currently you can add data sources and collections only via `local.metadata.yaml`, the support th' UI is still in progress.
