### ISSUE TITLE
infinity suggestions

### ISSUE THREAD

**Issue by michaelfeil** [truefoundry/cognita#214]
Cool work! Might feature it on Social Media / Twitter.

I recently added multi-model deployments that default to the ENV variables. Aka you can set the default env variable 
-> `--port` -> `INFINITY_PORT` or `--batch-size` -> `INFINITY_BATCH_SIZE`. Multiple args can be separated with `;`, which works if the cli arg can be overloaded. 

```bash
--model-id ${INFINITY_EMBEDDING_MODEL} --model-id ${INFINITY_RERANKING_MODEL}
```

```bash
INFINITY_MODEL_ID=mixedbread-ai/mxbai-embed-large-v1;mixedbread-ai/mxbai-rerank-xsmall-v1;
```

https://huggingface.co/spaces/michaelfeil/infinity/tree/305b1c2b583e9968aa153c45e8e50555af1d9575

**Comment by S1LV3RJ1NX** [comment]
Thanks for the suggestion, we shall check this and implement!
