### ISSUE TITLE
DNS resolution failed for qdrant-server:6334

### ISSUE THREAD

**Issue by cocobeach** [truefoundry/cognita#218]
The requirements.txt install pydantic2 but there is a fair deal of call deprecated like @parse_obj needing to be replaced with model_validate and so on.

After attempting to make the changes I am still having an error I can't resolve 

python -m local.ingest
VECTOR_DB_CONFIG: provider='qdrant' local=None url='http://qdrant-server:6333' api_key=None config=None
METADATA_STORE_CONFIG: provider='local' config={'path': 'local.metadata.yaml'}
Settings:  LOG_LEVEL='info' METADATA_STORE_CONFIG=MetadataStoreConfig(provider='local', config={'path': 'local.metadata.yaml'}) VECTOR_DB_CONFIG=VectorDBConfig(provider='qdrant', local=None, url='http://qdrant-server:6333', api_key=None, config=None) TFY_SERVICE_ROOT_PATH='/' TFY_API_KEY='' OPENAI_API_KEY=None TFY_HOST='' TFY_LLM_GATEWAY_URL='/api/llm' EMBEDDING_CACHE_CONFIG=None LOCAL=False OLLAMA_URL='http://ollama-server:11434' EMBEDDING_SVC_URL='http://infinity-server:7997' RERANKER_SVC_URL='http://infinity-server:7997' ollama_model='qwen2:1.5b' ollama_port=11434 infinity_embedding_model='mixedbread-ai/mxbai-embed-large-v1' infinity_reranking_model='mixedbread-ai/mxbai-rerank-xsmall-v1' infinity_batch_size=8 infinity_port=7997 cognita_backend_port=8000 cognita_backend_host='0.0.0.0' cognita_frontend_port=5001 vite_qa_foundry_url='http://cognita-backend:8000' vite_docs_qa_delete_collections='true' vite_docs_qa_standalone_path='/' vite_docs_qa_enable_redirect='false' vite_docs_qa_max_upload_size_mb=200
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/maxtensor/Documents/cognita/local/ingest.py", line 6, in <module>
    from backend.indexer.indexer import ingest_data as ingest_data_to_collection
  File "/home/maxtensor/Documents/cognita/backend/indexer/indexer.py", line 14, in <module>
    from backend.modules.metadata_store.client import METADATA_STORE_CLIENT
  File "/home/maxtensor/Documents/cognita/backend/modules/metadata_store/client.py", line 4, in <module>
    METADATA_STORE_CLIENT = get_metadata_store_client(config=settings.METADATA_STORE_CONFIG)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxtensor/Documents/cognita/backend/modules/metadata_store/base.py", line 212, in get_metadata_store_client
    return METADATA_STORE_REGISTRY[config.provider](config=config.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxtensor/Documents/cognita/backend/modules/metadata_store/local.py", line 56, in __init__
    associated_data_sources[self.data_source.fqn] = AssociatedDataSources(
                                                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxtensor/Documents/cognita/venv/lib/python3.11/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for AssociatedDataSources
data_source_fqn
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
    
    If somebody is working at updating to pydantic2 and knows what is going on? 
    Or have just gone down a rabbit hole to deep to get out?

**Comment by cocobeach** [comment]
so I erased everything and started fresh my .env point towards 6333 for qdrant that is running on 6333 but I keep getting this error, any idea of what else I should change into 6333

        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-06-14T06:05:20.216584739+01:00", grpc_status:14, grpc_message:"DNS resolution failed for qdrant-server:6334: C-ares status is not ARES_SUCCESS qtype=A name=qdrant-server is_balancer=0: Could not contact DNS servers"}"
        
        In qdrant.py it's specified like so self.port = 443 if self.url.startswith("https://") else 6333
        
        
>the only place I can see the 6334 port is in the docker compose the I am to using because I am running local: 

qdrant-server:
        image: qdrant/qdrant:v1.8.4
        pull_policy: if_not_present
        restart: unless-stopped
        container_name: qdrant
        ports:
            - 6333:6333
            - 6334:6334
        expose:
            - 6333
            - 6334
            - 6335
        volumes:
            - ./volumes/qdrant_storage:/qdrant/storage:z
        networks:
            - cognita-docker
            
Can somebody help please?

**Comment by chiragjn** [comment]
Even though we install pydantic v2 the code uses `pydantic.v1` till we get around to changing all models to v2.
As for the grpc issue, I think we have missed checking for non SSL case, let us fix that

**Comment by cocobeach** [comment]
I am running on Ubuntu 22.04.4 LTS, Docker version 26.1.4, build 5650f9b

But that's qdrant running on docker, running fine

           _                 _    
  __ _  __| |_ __ __ _ _ __ | |_  
 / _` |/ _` | '__/ _` | '_ \| __| 
| (_| | (_| | | | (_| | | | | |_  
 \__, |\__,_|_|  \__,_|_| |_|\__| 
    |_|                           

Version: 1.9.5, build: ba82f601
Access web UI at http://localhost:6333/dashboard

For cognita trying to run docker, I have this error:

docker-compose --env-file compose.env up --build --force-recreate
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.cognita-frontend.depends_on contains unsupported option: 'restart'
services.cognita-backend.depends_on contains unsupported option: 'restart'

But the problem is that even in a pip install without any mention of 6334 anywhere but in the docker compose, it is still looking for qdrant on 6334 and not on 6333 as specified in the .env, and exactly where my qdrant is up and running, and I tried with a local and a docker qdrant nothing is accessible from cognita.

I also understand that the local version doesn't support collection creation from the interface, so ATM it's still a work in progress?

So I tried the online version but I can't seem to be able to pull anything from github, it jut son;t create a collection neither, my idea would have been to link this step to the the foundry fine tuning framework and have an end-to-end fine-tuning tool on specialised datasets (I have developed the dataset creation script that I wanted to integrate in a new tab, because it seems to be the missing link, but I haven't looked into step 2 already because I am stuck on cognita not working no matter what combination of local or docker config I try.

quandrant work, infinity works, the vector db file was un-commented.

Another question is on qdrant's yaml dev & prod  we have a configuration for grcp which is commented like so:

service:
  host: 127.0.0.1
  http_port: 6333
  # Uncomment to enable gRPC:
  #grpc_port: 6334
  #api_key: your_secret_api_key_here
  
  on config.yaml we have this:
  
    # HTTP(S) port to bind the service on
  http_port: 6333

  # gRPC port to bind the service on.
  # If `null` - gRPC is disabled. Default: null
  # Comment to disable gRPC:
  grpc_port: 6334
  
If that is the problem, maybe we should mention it on the readme file, I am going to try but building qdrant takes quite a long time on my xeon cpu, so Id' like to know before I waste another day trying to get anythig to work?

Sorry for the inconvenience, and thank you for your help!

**Comment by chiragjn** [comment]
> But the problem is that even in a pip install without any mention of 6334 anywhere but in the docker compose, it is still looking for qdrant on 6334 and not on 6333 as specified in the .env,

This is expected, the current code sets prefer_grpc True when url is not using a `https://` url. And qdrant's grpc port is 6334
It seems like grpc is not able to resolve DNS correctly in your case

You can try one thing
set `self.prefer_grpc = False` on this line:
https://github.com/truefoundry/cognita/blob/ecedc7fa2686afd5919ba67bb213d2034f8c7db4/backend/modules/vector_db/qdrant.py#L32

I have started #221 which makes prefer_grpc False and allows passing more options for qdrant client

**Comment by cocobeach** [comment]
I already have it set as false: 

class QdrantVectorDB(BaseVectorDB):
    def __init__(self, config: VectorDBConfig):
        if config.local is True:
            self.local = True
            self.location = config.url
            self.qdrant_client = QdrantClient(
                path="./qdrant_db",
            )
        else:
            self.local = False
            self.url = config.url
            self.api_key = config.api_key
            self.port = 443 if self.url.startswith("https://") else 6333
            self.prefix = config.config.get("prefix", None) if config.config else None
     ==> self.prefer_grpc = False if self.url.startswith("https://") else True
            self.qdrant_client = QdrantClient(
                url=self.url,
                **({"api_key": self.api_key} if self.api_key else {}),
                port=self.port,
                prefer_grpc=self.prefer_grpc,
                prefix=self.prefix,
                timeout=300,
            )

**Comment by cocobeach** [comment]
(I am also not able to create collections on the online version btw)

**Comment by chiragjn** [comment]
> I already have it set as false:
> ==> self.prefer_grpc = False if self.url.startswith("https://") else True

This is not set to False, this will evaluate to True because we configure qdrant url with `http://`
https://github.com/truefoundry/cognita/blob/9a861a20ad532c09cb7ecddf08e425e83c957307/compose.env#L20

Anyway, we have merged #221 
Please pull `main` branch and recreate containers via docker compose

It should use qdrant via HTTP APIs now
