### ISSUE TITLE
Frontend Dockerfile ARG Error

### ISSUE THREAD

**Issue by Seuleeee** [truefoundry/cognita#225]
### Description
The current Frontend Dockerfile does not set the environment variables correctly using ARG and ENV instructions. This results in the build failing when these variables are needed during the build process.

* OS : MacOS (M1)

![image](https://github.com/truefoundry/cognita/assets/53285882/0490b477-d06d-4ae3-8d57-8886dd1bf524)

I'll push it!

**Comment by chiragjn** [comment]
Thanks for reporting and fixing this 🙌

**Comment by Seuleeee** [comment]
Thx!!! You guys provide such a nice app!
