### ISSUE TITLE
Its not allowed to add a web data source to the collection

### ISSUE THREAD

**Issue by AtmehEsraa** [truefoundry/cognita#276]
![image](https://github.com/user-attachments/assets/d4e03f1f-7e64-492c-bfd5-61c60a439cbf)
as its shown in paragraph we cant add it, how could I use it !

**Comment by S1LV3RJ1NX** [comment]
Can you pull the latest commit and let us know what is the error? Also try building the frontend image, it does not seem to be updated.

**Comment by AtmehEsraa** [comment]
@S1LV3RJ1NX  now its work, but I cant add more than one web source inside a one collection, why ?

**Comment by S1LV3RJ1NX** [comment]
You can add, once the collection is created you can add multiple data sources.

**Comment by AtmehEsraa** [comment]
@S1LV3RJ1NX  yes but not a web source, could you please try ?

**Comment by S1LV3RJ1NX** [comment]
Can you check if you have registered a new web data source? Then you can add it to the collection.

**Comment by S1LV3RJ1NX** [comment]
Yes you can.

**Comment by AtmehEsraa** [comment]
@S1LV3RJ1NX  What about the notification that tells us that the data will be public

**Comment by S1LV3RJ1NX** [comment]
That is only meant for cognita-public deployment. On prem data stays safe.
U can add basic auth to prevent anyone from accessing the collection. If
you are an enterprise or a small startup, Truefoundry can help you with the
same.

**Comment by AtmehEsraa** [comment]
@S1LV3RJ1NX  hi, this is the issue that I facing when try to add two links ,

![image](https://github.com/user-attachments/assets/d02612c7-1753-46af-b902-d12a609c8e2c)

and this is the way that I add the first link 

![image](https://github.com/user-attachments/assets/334c1c19-560a-450e-b615-258dc31145a4)

**Comment by chiragjn** [comment]
Closing this, please feel free to open this if you still run into this issue on latest main
