### ISSUE TITLE
Missing parsers.requirements.txt file when building Docker image in main branch

### ISSUE THREAD

**Issue by roggenkamps** [truefoundry/cognita#279]
Results when attempting to build Docker image from main branch:

> => [cognita-backend internal] load build definition from Dockerfile                                 0.0s
 => => transferring dockerfile: 2.21kB                                                               0.0s
 => [cognita-backend internal] load metadata for docker.io/library/python:3.11                       1.5s
 => [cognita-backend internal] load .dockerignore                                                    0.0s
 => => transferring context: 307B                                                                    0.0s
 => [cognita-backend internal] load build context                                                    0.1s
 => => transferring context: 14.37kB                                                                 0.0s
 => CANCELED [cognita-backend  1/11] FROM docker.io/library/python:3.11@sha256:c5254471e6073d894209  0.1s
 => => resolve docker.io/library/python:3.11@sha256:c5254471e6073d8942091227f469302f85b30d4b2307722  0.0s
 => => sha256:c5254471e6073d8942091227f469302f85b30d4b23077226f135360491f5226a 9.72kB / 9.72kB       0.0s
 => => sha256:c46ac9d8bd9fbabb71f5019489a49874d0ef2cc8382d0d5ab732f50741082d84 2.52kB / 2.52kB       0.0s
 => => sha256:a0535efbb274b9b26122ee2c1346a0db4368147d00371ba1ba2ec8a1269963ad 7.32kB / 7.32kB       0.0s
 => CACHED [cognita-backend  2/11] RUN apt-get update -y && apt-get install ffmpeg libsm6 libxext6   0.0s
 => CACHED [cognita-backend  3/11] RUN python3 -m venv /virtualenvs/venv/                            0.0s
 => CACHED [cognita-backend  4/11] COPY backend/requirements.txt /tmp/requirements.txt               0.0s
 => CACHED [cognita-backend  5/11] COPY backend/vectordb.requirements.txt /tmp/vectordb.requirement  0.0s
 => ERROR [cognita-backend  6/11] COPY backend/parsers.requirements.txt /tmp/parsers.requirements.t  0.0s
------
 > [cognita-backend  6/11] COPY backend/parsers.requirements.txt /tmp/parsers.requirements.txt:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref 0e730370-0c3c-4c6d-bae5-9a5f3238ffc4::rc8dik8gdjfht5j55pwgb59am: "/backend/parsers.requirements.txt": not found

It appears the parsers.requirements.txt file was recently removed, but I'm assuming the Dockerfile was not updated to match.

I plan to test this out and submit a pull if this is correct.

**Comment by S1LV3RJ1NX** [comment]
@roggenkamps thanks! this is fixed in #283
