### ISSUE TITLE
Github Security Lab Vulnerability Report

### ISSUE THREAD

**Issue by Kwstubbs** [truefoundry/cognita#304]
Greetings Cognita maintainers,

Github has found a potentail vulnerability in Cognita. Please let us know of a point of contact so that we can discuss this privately. We have the [Private Vulnerability Reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) feature if you do not have an established point of contact.

Thanks,
Kevin

**Comment by agutgutia1991** [comment]
Hi Kevin! Please share on email to ***@***.*** ,
***@***.*** , ***@***.*** and
***@***.***

**Comment by Kwstubbs** [comment]
@agutgutia1991 It seems the emails have been censored.

**Comment by chiragjn** [comment]
Hey @Kwstubbs, I have enabled Private Vulnerability Reporting for this repository. 
You can also reach out to us on cognita-support@truefoundry.com

**Comment by chiragjn** [comment]
I am closing this as we have not heard back. Please feel free to submit via Private Vulnerability Reporting, we'll be happy to address any issues

**Comment by Kwstubbs** [comment]
@chiragjn I have submitted a report in Private Vulnerability Reporting. Can you let me know if you have seen it?

**Comment by chiragjn** [comment]
I have accepted it now, sorry for the delay and again thank you so much for submitting, we'll get them fixed
