### ISSUE TITLE
Failed to Add Document to Collection 

### ISSUE THREAD

**Issue by clive97** [truefoundry/cognita#307]
Hi,

I’m encountering an issue while trying to add documents to existing Collections using the "Add Data Source" feature. The error message I’m seeing is:

ERROR:    2024-08-16 18:13:33,350 - prismastore:aassociate_data_source_with_collection:254 - Error: 'dict' object has no attribute 'dict'
cognita-backend   | Traceback (most recent call last):
cognita-backend   |   File "/app/backend/modules/metadata_store/prismastore.py", line 245, in aassociate_data_source_with_collection
cognita-backend   |     associated_data_sources[data_source_fqn] = data_source.dict()
cognita-backend   |                                                ^^^^^^^^^^^^^^^^
cognita-backend   | AttributeError: 'dict' object has no attribute 'dict'

It looks like there is an attempt to call the dict() method on a dictionary object, which is causing this error.  Any advice or suggestions on how to resolve this would be greatly appreciated.

Thanks,
Clive

**Comment by chiragjn** [comment]
Hey clive97,
Can you please try with the latest code on main branch?

We recently moved to pydantic v2 and your traceback seems to reference older code. It is possible there is some mismatch in dependencies and code in your instance.

**Comment by clive97** [comment]
Thanks so much for the help!  It is resolved now by redeploying the platform with the latest commit in main.

-Clive
