### ISSUE TITLE
Unstructured parser api calls should be async (httpx / aiohttp)

### ISSUE THREAD

**Issue by chiragjn** [truefoundry/cognita#327]
Currently unstructured parser api calls are sync calls made with requests library. We should just use httpx / aiohttp to make them async.

**Comment by Blakeinstein** [comment]
Taking this up as well!

**Comment by mnvsk97** [comment]
Let's use their official python sdk: https://github.com/Unstructured-IO/unstructured-python-client

**Comment by chiragjn** [comment]
I was thinking, should we instead get rid of async everywhere and let fastapi starlette threadpool handle the concurrency?
Anyway indexing is offloaded to another process / external worker

**Comment by chiragjn** [comment]
Closing this because this has been addressed to a decent extent now - we are in the process of removing async from many places
